# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  group: VeracodeScanning

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: build_application
    displayName: 'Build Application'
    container: node:latest
    steps:
    - script: |
        apt-get update
        apt-get install -y zip
      displayName: 'Install dependencies'

    - script: |
        npm ci --cache .npm --prefer-offline
      displayName: 'Install npm packages'

    - script: |
        zip -R NodeGoat.zip '*.js' -x '*node_modules*'
      displayName: 'Package application'

- stage: Security
  jobs:
  - job: security_scan
    displayName: 'Security Scan'
    steps:
    - task: VeracodeScanning@0
      displayName: 'Run Veracode Scanning'
